services:
  protonmail-bridge:
    build: .
    image: protonmail-bridge:local
    container_name: protonmail-bridge
    volumes:
      - bridge_data:/root
    ports:
      - "${IMAP_PORT}:143"
      - "${SMTP_PORT}:25"
    restart: unless-stopped

volumes:
  bridge_data:
